# If not running interactively, don't do anything
[ -z "$PS1" ] && return

OS=$(uname)

if [ $OS == "Darwin" ]; then
  export EDITOR='sublime -w'
else
  export EDITOR=vim
fi

MITSUHIKOS_DEFAULT_COLOR="[00m"
MITSUHIKOS_GRAY_COLOR="[37m"
MITSUHIKOS_PINK_COLOR="[35m"
MITSUHIKOS_GREEN_COLOR="[32m"
MITSUHIKOS_ORANGE_COLOR="[33m"
MITSUHIKOS_RED_COLOR="[31m"
if [ `id -u` == '0' ]; then
  MITSUHIKOS_USER_COLOR=$MITSUHIKOS_RED_COLOR
else
  MITSUHIKOS_USER_COLOR=$MITSUHIKOS_PINK_COLOR
fi
MITSUHIKOS_VCPROMPT_EXECUTABLE=~/bin/vcprompt

mitsuhikos_vcprompt() {
  $MITSUHIKOS_VCPROMPT_EXECUTABLE -f $' on \033[34m%n\033[00m:\033[00m%[unknown]b\033[32m%m%u'
}

mitsuhikos_lastcommandfailed() {
  code=$?
  if [ $code != 0 ]; then
    echo -n $'\033[37m exited \033[31m'
    echo -n $code
    echo -n $'\033[37m'
  fi
}

mitsuhikos_backgroundjobs() {
  jobs|python -c 'if 1:
    import sys
    items = ["\033[36m%s\033[37m" % x.split()[2]
             for x in sys.stdin.read().splitlines()]
    if items:
      if len(items) > 2:
        string = "%s, and %s" % (", ".join(items[:-1]), items[-1])
      else:
        string = ", ".join(items)
      print "\033[37m running %s" % string
  '
}

mitsuhikos_virtualenv() {
  if [ x$VIRTUAL_ENV != x ]; then
    echo -n $' \033[37mworkon \033[31m'
    basename "${VIRTUAL_ENV}"
    echo -n $'\033[00m'
  fi
}

export MITSUHIKOS_BASEPROMPT='\n\e${MITSUHIKOS_USER_COLOR}\u \
\e${MITSUHIKOS_GRAY_COLOR}at \e${MITSUHIKOS_ORANGE_COLOR}\h \
\e${MITSUHIKOS_GRAY_COLOR}in \e${MITSUHIKOS_GREEN_COLOR}\w\
`mitsuhikos_lastcommandfailed`\
\e${MITSUHIKOS_GRAY_COLOR}`mitsuhikos_vcprompt`\
`mitsuhikos_backgroundjobs`\
`mitsuhikos_virtualenv`\
\e${MITSUHIKOS_DEFAULT_COLOR}'
export PS1="${MITSUHIKOS_BASEPROMPT}
$ "

export TERM=xterm-color
export GREP_OPTIONS='--color=auto' GREP_COLOR='1;32'
export CLICOLOR=1
if [ `uname` == "Darwin" ]; then
  export LSCOLORS=ExGxFxDxCxHxHxCbCeEbEb
  export LC_CTYPE=en_US.utf-8
else
  alias ls='ls --color=auto'
fi

alias git=hub
alias rvim="gvim --remote-silent"
shopt -s histappend

if [ -f /usr/local/git/contrib/completion ]; then
  . /usr/local/git/contrib/completion/git-completion.bash
fi
if [ -f /etc/bash_completion ]; then
  . /etc/bash_completion
fi

# hack to get ppc out of that thing
export ARCHFLAGS="-arch i386 -arch x86_64"

# add some bins
export PATH=$PATH:/usr/local/bin:/usr/local/sbin:~/bin

# Subversion
svndiff()
{
  svn diff "${@}" | colordiff | less -R
}
alias svn="/usr/bin/svn --username gzangirolami $*"

if [ -f /opt/subversion/bin ]; then
  export PATH=/opt/subversion/bin:$PATH
  alias svn17="/opt/subversion/bin/svn $0"
fi

# Virtualenvwrapper and pip settings
export WORKON_HOME=$HOME/.virtualenv
export PIP_VIRTUALENV_BASE=$WORKON_HOME
export PIP_RESPECT_VIRTUALENV=true
export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python
VIRTUAL_ENV_DISABLE_PROMPT=1

if [ -f /usr/local/bin/virtualenvwrapper.sh ]; then
  source /usr/local/bin/virtualenvwrapper.sh
fi

# MySQL aliases
if [ -d /usr/local/mysql/bin ]; then
  export PATH=$PATH:/usr/local/mysql/bin
  alias mysql=/usr/local/mysql/bin/mysql
  alias mysqladmin=/usr/local/mysql/bin/mysqladmin
  alias mysqldump=/usr/local/mysql/bin/mysqldump
fi

# Git autocompletion with HUB
if [ -f  /usr/local/git/contrib/completion/git-completion.bash ]; then
  source /usr/local/git/contrib/completion/git-completion.bash
fi

# Environment quick aliases
function quick_env() {
    workon $1 && cd $HOME/Code/$1
}

function runserver_auto() {
    if [ "$1" == "public" ]; then
        ip=`python -c "from urllib import urlopen; print urlopen('http://automation.whatismyip.com/n09230945.asp').read()"`
    else
	    ip=`python -c "import socket; print socket.gethostbyname(socket.gethostname())"`
    fi
    echo "Starting server on $ip"
    python manage.py runserver $ip:8000
}
alias runserver="runserver_auto"

# VPN Aliases
alias cisco_vpn="/opt/cisco/vpn/bin/vpn"

# Git Flags - TODO: move to gitconfig
export GIT_DISCOVERY_ACROSS_FILESYSTEM=0
export GIT_SSL_NO_VERIFY=true
alias gitlog="git log --stat --color --pretty='%n%H %Cred %aN %Cblue %aD %n %Cgreen %s %Creset'"
alias gitdiff="git diff --color"
alias gitstat="git diff --color --stat"

# Postgres OSX
if [ -d /Library/PostgreSQL/8.4/bin ]; then
  alias psql="/Library/PostgreSQL/8.4/bin/psql"
  alias postgres_start="sudo /Library/PostgreSQL/8.4/bin/pg_ctl -D /Library/PostgreSQL/8.4/data start"
fi

# Erlang Sucks
if [ -d /usr/share/erlang ]; then
  ERLANG_HOME=/usr/share/erlang
  PATH=$PATH:$ERLANG_HOME/bin
fi

# Pear - PHP
if [ -f $HOME/.pear/bin ]; then
  PATH=$PATH:$HOME/.pear/bin
fi

# Bash aliases
# ls with entire path
alias lsp="printf '$PWD/%s\n' *"

# Python brew
if [ -f $HOME/.pythonbrew/etc/bashrc ]; then
  source $HOME/.pythonbrew/etc/bashrc
fi

# Perl
if [ -f $HOME/perl5/perlbrew/etc/bashrc ]; then
  PERL_CPANM_OPT="--local-lib=~/perl5"
  source ~/perl5/perlbrew/etc/bashrc
  export PATH=$PATH:~/perl5/bin
fi

# Node JS
if [ -d /usr/local/lib/node_modules ]; then
  export NODE_PATH="/usr/local/lib/node_modules"
fi

# Set default terminal to UTF-8
export LANG=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8

# Use bash-completion, if available
# cf. http://meinit.nl/bash-completion-mac-os-x
# cf. http://mult.ifario.us/p/getting-bash-completion-magic-on-os-x
[ -f /usr/local/etc/bash_completion ] && . /usr/local/etc/bash_completion

# CD laziness
alias ..="cd .."
alias ...="cd ../../"
alias ....="cd ../../../"

# Private bash settings
if [ -f $HOME/.bash_private ]; then
  . $HOME/.bash_private
fi

if [ -f $HOME/bash_completion/knife ]; then
  . $HOME/bash_completion/knife
fi
